name: CI Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: verify commits
        run: TRIGGER_BRANCH=$GITHUB_REF_NAME ./hack-kni/verify-commits.sh
